project_id = "lujdjwqbsqterbcvzyvo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false

[functions.calculate-delivery-fee]
verify_jwt = false

[functions.calculate-eta]
verify_jwt = false

[functions.create-mercadopago-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false
